# Site settings
title: Liubin Feng|冯柳宾
email: pigeonfeng@gmail.com
description: ""
baseurl: "/"
url: "http://liubin.name"
github_username:  fenglb

# Build settings
markdown: kramdown
permalink: pretty
