# Site settings
title: Liubin Feng|冯柳宾
email: pigeonfeng@gmail.com
description: "Personal webisite of Liubin Feng; 冯柳宾的个人网站"
baseurl: ""
url: "http://liubin.name"
github_username:  fenglb

# Build settings
markdown: kramdown
permalink: pretty
